-- MySQL Script generated by MySQL Workbench
-- Thu Oct 28 16:05:58 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`NutriScore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`NutriScore` (
  `idNutriScore` INT NOT NULL,
  `valeur` VARCHAR(1) NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idNutriScore`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Marque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Marque` (
  `idMarque` INT GENERATED ALWAYS AS () VIRTUAL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMarque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categorie` (
  `idCategorie` INT GENERATED ALWAYS AS () VIRTUAL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produit` (
  `idProduit` INT GENERATED ALWAYS AS () VIRTUAL,
  `nom` VARCHAR(45) NOT NULL,
  `référence` VARCHAR(45) NOT NULL,
  `NutriScore_idNutriScore` INT NOT NULL,
  `Marque_idMarque` INT NOT NULL,
  `NutriScore_idNutriScore1` INT NOT NULL,
  `Marque_idMarque1` INT NOT NULL,
  `Produit_idProduit` INT NOT NULL,
  `Produit_Marque_idMarque` INT NOT NULL,
  `Categorie_idCategorie` INT NOT NULL,
  PRIMARY KEY (`idProduit`, `Marque_idMarque`),
  INDEX `fk_Produit_NutriScore_idx` (`NutriScore_idNutriScore1` ASC) VISIBLE,
  INDEX `fk_Produit_Marque1_idx` (`Marque_idMarque1` ASC) VISIBLE,
  INDEX `fk_Produit_Categorie1_idx` (`Categorie_idCategorie` ASC) VISIBLE,
  CONSTRAINT `fk_Produit_NutriScore`
    FOREIGN KEY (`NutriScore_idNutriScore1`)
    REFERENCES `mydb`.`NutriScore` (`idNutriScore`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_Marque1`
    FOREIGN KEY (`Marque_idMarque1`)
    REFERENCES `mydb`.`Marque` (`idMarque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_Categorie1`
    FOREIGN KEY (`Categorie_idCategorie`)
    REFERENCES `mydb`.`Categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingredient` (
  `idIngredient` INT GENERATED ALWAYS AS () VIRTUAL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idIngredient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Additif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Additif` (
  `idAdditif` INT GENERATED ALWAYS AS () VIRTUAL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdditif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Allergene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Allergene` (
  `idAllergene` INT GENERATED ALWAYS AS () VIRTUAL,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAllergene`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ValeurNutritionnelle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ValeurNutritionnelle` (
  `idNutriscore` INT NOT NULL,
  `Nutriscorecol` VARCHAR(45) NULL,
  `vit_A` DOUBLE NULL,
  `vit_B` DOUBLE NULL,
  `vit_C` DOUBLE NULL,
  `huileDePalme` TINYINT NULL,
  `Produit_idProduit` INT NOT NULL,
  `Produit_Marque_idMarque` INT NOT NULL,
  PRIMARY KEY (`idNutriscore`),
  INDEX `fk_ValeurNutritionnelle_Produit1_idx` (`Produit_idProduit` ASC, `Produit_Marque_idMarque` ASC) VISIBLE,
  CONSTRAINT `fk_ValeurNutritionnelle_Produit1`
    FOREIGN KEY (`Produit_idProduit` , `Produit_Marque_idMarque`)
    REFERENCES `mydb`.`Produit` (`idProduit` , `Marque_idMarque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredient_has_Produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingredient_has_Produit` (
  `id_ingredient_produit` INT NOT NULL,
  `id_produit` INT NOT NULL,
  `id_ingredient` INT NOT NULL,
  PRIMARY KEY (`id_ingredient_produit`, `id_produit`, `id_ingredient`),
  INDEX `fk_Ingredient_has_Produit_Produit1_idx` (`id_produit` ASC) VISIBLE,
  INDEX `fk_Ingredient_has_Produit_Ingredient1_idx` (`id_ingredient` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredient_has_Produit_Ingredient1`
    FOREIGN KEY (`id_ingredient`)
    REFERENCES `mydb`.`Ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingredient_has_Produit_Produit1`
    FOREIGN KEY (`id_produit`)
    REFERENCES `mydb`.`Produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produit_has_Additif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produit_has_Additif` (
  `id_additif_produit` INT NOT NULL,
  `id_produit` INT NOT NULL,
  `id_additif` INT NOT NULL,
  PRIMARY KEY (`id_additif_produit`, `id_produit`, `id_additif`),
  INDEX `fk_Produit_has_Additif_Additif1_idx` (`id_additif` ASC) VISIBLE,
  INDEX `fk_Produit_has_Additif_Produit1_idx` (`id_produit` ASC) VISIBLE,
  CONSTRAINT `fk_Produit_has_Additif_Produit1`
    FOREIGN KEY (`id_produit`)
    REFERENCES `mydb`.`Produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_has_Additif_Additif1`
    FOREIGN KEY (`id_additif`)
    REFERENCES `mydb`.`Additif` (`idAdditif`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produit_has_Allergene`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produit_has_Allergene` (
  `id_allergene_produit` INT NOT NULL,
  `id_produit` INT NOT NULL,
  `id_allergene` INT NOT NULL,
  PRIMARY KEY (`id_allergene_produit`, `id_produit`, `id_allergene`),
  INDEX `fk_Produit_has_Allergene_Allergene1_idx` (`id_allergene` ASC) VISIBLE,
  INDEX `fk_Produit_has_Allergene_Produit1_idx` (`id_produit` ASC) VISIBLE,
  CONSTRAINT `fk_Produit_has_Allergene_Produit1`
    FOREIGN KEY (`id_produit`)
    REFERENCES `mydb`.`Produit` (`idProduit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produit_has_Allergene_Allergene1`
    FOREIGN KEY (`id_allergene`)
    REFERENCES `mydb`.`Allergene` (`idAllergene`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
